# Generated by Django 5.1.1 on 2024-09-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('itemDescription', models.TextField()),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemStock', models.IntegerField(max_length=999)),
                ('itemCategory', models.TextField()),
                ('itemUploaded', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
