# Generated by Django 5.1.1 on 2024-09-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_id_alter_product_itemstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='itemUploaded',
        ),
    ]
