# Generated by Django 5.1.1 on 2024-09-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_itemuploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itemImageURL',
            field=models.URLField(default='http://example.com'),
        ),
    ]
